### ISSUE TITLE
Remove my personal details from Bioinformatics and Contact us pages

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-project.github.io#16]
http://preview.cyclone-project.eu/usecases/1-bioinformatics.html
in paragraph "Have a chat with Christophe"

http://preview.cyclone-project.eu/contact.html
in paragraph "Use Case: Bioinformatics"

I would prefer that these contacts go through a form.

**Comment by mathiasslawik** [comment]
Hi Christophe. I've removed all personal contact data from the repository.
