### ISSUE TITLE
Update the text for Energy Use Case and for the QSC 

### ISSUE THREAD

**Issue by qshacker** [cyclone-project/cyclone-project.github.io#17]
Please consider the changes provided in the email on 8 September 2016 concerning  the Energy Use Case and the text provided for QSC in the section with the members of team.

**Comment by mathiasslawik** [comment]
Hello,

I added the requested changes in https://github.com/cyclone-project/cyclone-project.github.io/commit/b8bf68dda444995ec33e9f5e4974851fcd3bb835.

If you find time, you could still optimize the website use case description a bit more. I would propose to be more concrete, especially on:
- The way CYCLONE is used, e.g., using SlipStream for creating deployment modules
- The concrete benefits for the VPP, e.g., rapid deployment in DERs

In the same way you're concrete about your CYCYLONE involvement, you could tune down the information about renewable energy. A stucture proposal would be: 
- How the future energy sector will benefit from CYCLONE?
- What are the concrete actions and expected results?
- How will this help our planet?

Best regards,
Mathias
