### ISSUE TITLE
Change title and include description for CNSMO in "tools" section

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-project.github.io#19]
In the "tools" section of the website cold you please:

1.- Change "Cyclone Networking Services Manager and Orchestrator" and put instead "CYCLONE Networking Services Manager and Orchestrator - CNSMO"

2.- Change the subtitle " Integrate network services into your cloud applications using our ready-to-deploy modules to increase security and lower maintenance efforts" and put instead: 

"_Integrate network services into your cloud applications using our ready-to-deploy modules in an automated way_."

3.- After the subtitle remove "i2Cat?, Source" and put instead:

"i2CAT, GPLv3, Source"

*(the Source is correct)

4.- Include the following description:

"_OpenNaaS-CNSMO is a lightweight distributed platform responsible of deploying, configuring and running the networking services in Cyclone project by defining a basic service API and service lifecycle, together with an interservice communication mechanism implementing the actor model and supporting different communication protocols. The system is capable of deploying and running multiple services in both local and remote environments. CNSMO is composed by two components:
             - The CNSMO core
             - CNSMO agents running networking services"

**Comment by mathiasslawik** [comment]
OK. Done in https://github.com/cyclone-project/cyclone-project.github.io/commit/ff06d63286dce12ea16ac91c0a6d8113b20c4d83
