### ISSUE TITLE
Where are the "PERSONAS" stuff?

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-project.github.io#20]
I believe the PERSONAS reasoning is nowhere in the website. It should be included and related to the other aspects of th website to highlight the target audience of CYCLONE. ALso because we are linking it to other CYCLONE topics as for instance the  innovation management.

**Comment by mathiasslawik** [comment]
Hi José,

the personas were never meant to be displayed to our users, but were a guide for creating content that matters to our target groups.

I used them extensively on the website, for example, to structure the landing page into three main areas:
- DevOps tools -> Doreen
- Research -> Ricky
- Use Cases -> Manny and Elena

Furthermore, I tried to implicitly target certain groups with the content I created. Others still need to check how the content we create (e.g., newsletters, news items) relate to our target group and make sure that we offer them something meaningful.

We can still discuss if we need to make it explicit, i.e., mark any content to whom it targets. Until now, I don't think this is a good idea as we see that some content will be pertinent to different groups in different context, e.g., the "tools" are relevant to Doreen (to use them), Manny (to place them in a strategy), Ricky (to use it as related work) so marking them "for all" would not provide any benefit.

Instead, we should make it clear (for ourselves) FIRST for who we write content THEN what they care about and THEN create the content, and not write it and then think about how we could market it.

But I see this is still an area for discussion.

Best regards,
Mathias
