### ISSUE TITLE
Include OpenNaaS CNSMO video demos in the website (inder "tools -->Demo applications").

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-project.github.io#22]
Hi @mathiasslawik 

Could you plase include the videos (or the link to the videos) in the website. Here you are the links:

CNSMO VPN service Demonstrator
https://www.youtube.com/watch?v=34nqiouZly4

CNSMO FW service Demonstrator
https://www.youtube.com/watch?v=e7JcFwJz-bA

CNSMO LB service Demonstrator
https://www.youtube.com/watch?v=IpPkZAAfqo8

**Comment by mathiasslawik** [comment]
Hello José,

I added the demo videos to both the "Tools" as well as the "Media" section in https://github.com/cyclone-project/cyclone-project.github.io/commit/3a49e005b71bc6b016946a5f47390c38fd730ca3

Best regards,
Mathias
